### ISSUE TITLE
[Question] Can I use this project to restore UART signals that have been converted by CH340?

### ISSUE THREAD

**Issue by liu2-3zhi** [atc1441/CH559sdccUSBHost#21]
I am looking to implement a functionality similar to STM32 → UART → CH340 →USB → CH559 →ESP32. I am hoping that the CH559 can utilize the USB host to restore the UART signals. Is this something that can be achieved with this project?

**Comment by GrantMTG** [comment]
I can't speak to the firmware part as I haven't made any changes yet (though I was planning to turn it back into a Keil uVision project), but hardware-wise it would work. Most expensive "wire-replacement" I've seen in a while though

So assuming you have this on the STM32 side:

STM32 → UART → CH340 (USB Device) → USB cable

I'm guessing the CH340 is USB Device to UART, I've never used one before.  And on the ESP32 side you'd have:

USB cable → CH559 (USB Host) → ESP32

then you'd need CDC (host) code for the CH559. I don't know if that exists (yet) or not. 


Now having said all that there are lots of more direct ways of connecting an ESP32 to an STM32.
