### ISSUE TITLE
Bluetooth mouse

### ISSUE THREAD

**Issue by modi12jin** [atc1441/CH559sdccUSBHost#4]
Can I use a Bluetooth mouse?  I think it's a cool idea

**Comment by atc1441** [comment]
Hi. 

A bluetooth mouse would not work with the CH559.
But the ESP32 has integrated Bluetooth so you can use that

**Comment by dtiziano** [comment]
So, do you think, it might be possible to convert a standard usb keyboard into a bluetooth keyboard using the esp32 integrated bluetooth module?

**Comment by atc1441** [comment]
Hi, yes defenetely that is no problem to build from this.
